name: Publish Docker image

on:
    push:
        branches:
          - main
        paths-ignore:
          - 'CHANGELOG.md'
          - '**/README.md'
          - 'docker-compose/*'

jobs:
    run:
        name: Run
        runs-on: ubuntu-latest
        steps:
            -   name: Check out the repo
                uses: actions/checkout@v4
    
            -   name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v3
    
            # Will automatically make nice tags, see the table here https://github.com/docker/metadata-action#basic
            -   name: Docker meta
                id: meta
                uses: docker/metadata-action@v5
                with:
                    images: omninetwork/explorer-frontend
    
            -   name: Login to GitHub Container Registry
                uses: docker/login-action@v2
                with:
                    username: ${{ secrets.DOCKER_USERNAME }}
                    password: ${{ secrets.DOCKER_PASSWORD }}
    
            -   name: Add SHORT_SHA env property with commit short sha
                run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV

            -   name: Debug
                env:
                    REF_TYPE: ${{ github.ref_type }}
                    REF_NAME: ${{ github.ref_name }}
                run: |
                    echo "ref_type: $REF_TYPE"
                    echo "ref_name: $REF_NAME"
    
            -   name: Build and push
                uses: docker/build-push-action@v5
                with:
                    context: .
                    file: ./Dockerfile
                    push: true
                    cache-from: type=gha
                    tags: ${{ inputs.tags || steps.meta.outputs.tags }}
                    platforms: |
                        linux/amd64
                    labels: ${{ steps.meta.outputs.labels }}
                    build-args: |
                        GIT_COMMIT_SHA=${{ env.SHORT_SHA }}
                        GIT_TAG=${{ github.ref_type == 'tag' && github.ref_name || '' }}